language: python

python:
  - "3.3"
  - "2.7"
  - "2.6"

install:
  - "pip install coverage"
  - "pip install coveralls"
  - "pip install flake8"

script:
  - "coverage run --source=p2048,test_p2048 setup.py test"

after_script:
  - "flake8 ."

after_success:
  - "coveralls"
