language: python

python:
  - "3.3"
  - "2.7"
  - "2.6"

install:
  - "pip install pytest-cov"
  - "pip install coverage"
  - "pip install coveralls"

script:
  - "python setup.py test"

after_success:
  - "coveralls"
